# Generated by Django 6.0 on 2026-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image behind the Who We Are / What We Do section.', null=True, upload_to='about/'),
        ),
    ]
