# Generated by Django 6.0 on 2026-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutinfo_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
