# Generated by Django 5.2.13 on 2026-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footerinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='A production company based in Iraq, Baghdad, specialized in producing documentary works. We are dedicated to capturing real-life stories and presenting them in a compelling and thought-provoking manner. Our mission is to shed light on important issues and bring untold narratives to the forefront of the global audience')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Description',
                'verbose_name_plural': 'Hero Description',
            },
        ),
    ]
