# Generated by Django 5.2.13 on 2026-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herodescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon. Should be a small square image with transparent background.', null=True, upload_to='site/'),
        ),
    ]
