# Generated by Django 5.2.13 on 2026-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footerinfo_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
