# Generated by Django 6.0.4 on 2026-04-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_footerinfo_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTSGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bts-gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BTS Gallery Image',
                'verbose_name_plural': 'BTS Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CastingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='casting/')),
                ('description', models.TextField(blank=True, help_text='Text shown over the background image (bottom-left).')),
                ('button_label', models.CharField(default='View on Instagram', max_length=100)),
                ('button_url', models.URLField(default='https://www.instagram.com/bsrcast/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Casting Page',
                'verbose_name_plural': 'Casting Page',
            },
        ),
    ]
