# Generated by Django 6.0 on 2026-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_btsgalleryimage_castingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='casting/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Casting Slide',
                'verbose_name_plural': 'Casting Slides',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='castingpage',
            name='headline',
            field=models.CharField(blank=True, help_text='Large headline shown above the description.', max_length=200),
        ),
    ]
