# Generated by Django 6.0 on 2026-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_casting_slide_and_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='best-works/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True, help_text='Optional URL to open when the image is clicked.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Best Work',
                'verbose_name_plural': 'Best Works',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
