# Generated by Django 6.0 on 2026-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bestwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Large headline, rendered in the GARO font (uppercase).', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Smaller body text under the title.')),
                ('label', models.CharField(blank=True, help_text="Optional small tag shown on the far left of the banner (e.g. 'AWARDS').", max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Use either an image OR a video, not both.', null=True, upload_to='banners/')),
                ('video', models.FileField(blank=True, help_text='Use either an image OR a video, not both.', null=True, upload_to='banners/')),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
