# Generated by Django 6.0 on 2026-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='production_quality',
            field=models.CharField(blank=True, help_text='Resolution, e.g. HD, 2K, 4K, 8K.', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='production_type',
            field=models.CharField(blank=True, help_text='e.g. Documentary, TVC, Music Video.', max_length=80),
        ),
        migrations.AddField(
            model_name='banner',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of production, e.g. 2025.', null=True),
        ),
    ]
