# Generated by Django 6.0.4 on 2026-04-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Description shown above the video.')),
                ('video', models.FileField(blank=True, help_text='Shown directly under the description.', null=True, upload_to='academy/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional external video URL (YouTube, Vimeo). Used if no uploaded video.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academy Item',
                'verbose_name_plural': 'Academy Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='academy/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.academyitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
